ALTER TABLE [dbo].[Users_Dynamics]
    ADD CONSTRAINT [PK_UsersDynamics] PRIMARY KEY CLUSTERED ([DynamicsId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

